services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://nest_user:nest_password@postgres:5432/nest_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:prod"

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
